### ISSUE TITLE
Unable to install gem via rake task

### ISSUE THREAD

**Issue by schof** [romul/spree-solr-search#1]
All rake tasks fail if you do not have aas gem installed ("no such file to load -- acts_as_solr/tasks")

Change `acts_as_solr.rake` as follows:

```
if defined? Solr::Document 
  require "acts_as_solr/tasks"
end
```

**Comment by schof** [comment]
Actually that does not work once gem is installed.  So use this instead

```
begin
  require "acts_as_solr/tasks"
rescue LoadError
  puts "WARNING: acts_as_solr_reloaded gem appears to be unavailable.  Please install with rake gems:install."
end
```

**Comment by romul** [comment]
Done: http://github.com/romul/spree-solr-search/commit/78547e80d7f224b8dd393bb68c1e51c526927e50
