### ISSUE TITLE
Ruby 1.9.2 and libxml-ruby

### ISSUE THREAD

**Issue by jumph4x** [romul/spree-solr-search#10]
Hey guys, 

Just solved an issue with acts_as_solr_reloaded (dependency), the gem version of 1.5.0 might have the bug still. 

To fix, include this before this extension (order wise) in your Gemfile:
gem "acts_as_solr_reloaded", :git => "git://github.com/dcrec1/acts_as_solr_reloaded.git"

The repository is of the author, so that's all good. 
See this if curious: https://github.com/dcrec1/acts_as_solr_reloaded/pull/11

**Comment by jumph4x** [comment]
acts_as_solr_reloaded author released 1.6.0 with the 1.9.2 fix. Creating pull request for a dependency version bump.

**Comment by romul** [comment]
https://github.com/romul/spree-solr-search/commit/2c1027f6e7a7469178eddf955d7e436ccc76aacc
