### ISSUE TITLE
Cannot modify SafeBuffer in place

### ISSUE THREAD

**Issue by maslof** [romul/spree-solr-search#16]
Hello!

Please, tell me why don't work rake solr:reindex BATCH=500?
trace mistake:

Requiring REXML
Clearing index for Product...
Rebuilding index for Product...
rake aborted!
Cannot modify SafeBuffer in place

Tasks: TOP => solr:reindex
(See full trace by running task with --trace)
antonio@antonio-P5KC:~/my_spree_site$ rake solr:reindex BATCH=500 --trace
Requiring REXML
*\* Invoke solr:reindex (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute solr:reindex
Clearing index for Product...
Rebuilding index for Product...
rake aborted!
Cannot modify SafeBuffer in place
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/activesupport-3.0.9/lib/active_support/core_ext/string/output_safety.rb:127:in `gsub!'
/home/antonio/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/rexml/text.rb:117:in`initialize'
/home/antonio/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/rexml/element.rb:494:in `new'
/home/antonio/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/rexml/element.rb:494:in`text='
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/acts_as_solr_reloaded-1.6.0/lib/solr/field.rb:32:in `to_xml'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/acts_as_solr_reloaded-1.6.0/lib/solr/document.rb:68:in`block in to_xml'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/acts_as_solr_reloaded-1.6.0/lib/solr/document.rb:68:in `each'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/acts_as_solr_reloaded-1.6.0/lib/solr/document.rb:68:in`to_xml'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/acts_as_solr_reloaded-1.6.0/lib/acts_as_solr/instance_methods.rb:81:in `to_solr_doc'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/acts_as_solr_reloaded-1.6.0/lib/acts_as_solr/class_methods.rb:219:in`block in rebuild_solr_index'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/acts_as_solr_reloaded-1.6.0/lib/acts_as_solr/class_methods.rb:219:in `collect'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/acts_as_solr_reloaded-1.6.0/lib/acts_as_solr/class_methods.rb:219:in`rebuild_solr_index'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/acts_as_solr_reloaded-1.6.0/lib/tasks/solr.rake:111:in `block (3 levels) in <top (required)>'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/acts_as_solr_reloaded-1.6.0/lib/tasks/solr.rake:102:in`each'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/acts_as_solr_reloaded-1.6.0/lib/tasks/solr.rake:102:in `block (2 levels) in <top (required)>'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:205:in`call'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:200:in`each'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
/home/antonio/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:112:in`invoke_task'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:90:in`each'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:129:in`standard_exception_handling'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:62:in`block in run'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:59:in`run'
/home/antonio/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/home/antonio/.rvm/gems/ruby-1.9.2-head/bin/rake:19:in`load'
/home/antonio/.rvm/gems/ruby-1.9.2-head/bin/rake:19:in `<main>'
Tasks: TOP => solr:reindex

**Comment by jumph4x** [comment]
REXML is in the trace. libxml2 is vastly faster. 

In your Gemfile, right above spree_solr_search, try including libxml2:

gem 'libxml-ruby'
gem 'spree_solr_search', :git => 'git://github.com/romul/spree-solr-search.git'
