### ISSUE TITLE
Problem with solr_search and spree-0.40

### ISSUE THREAD

**Issue by alx** [romul/spree-solr-search#5]
Hi,

I'm contacting you because I'm new with solr and spree, and you might be able to tell me straight away if I'm doing something wrong.

First, I'm using spree-0.40, there might be some compatibility issue. If so, please tell me what is needed to do, I'll start on this as soon as possible.

Then, my current problem:

Everything is installing fine, without particular problem on tomcat/solr/rails/rvm/passenger installation.

I'm trying the "_rake solr:reindex BATCH=500_" command, and I got this error:

```
Requiring REXML
** Invoke solr:reindex (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute solr:reindex
Clearing index for Product...
Rebuilding index for Product...
rake aborted!
400 "Bad Request"
```

In tomcat logs, I got this error:

```
==> catalina.2011-01-10.log <==
Jan 10, 2011 7:49:04 PM org.apache.solr.common.SolrException log
SEVERE: org.apache.solr.common.SolrException: ERROR:unknown field 'brand_property_facet'
at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:289)
at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:60)
```

On local install,  I've got this other error:

```
Requiring REXML
** Invoke solr:reindex (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
undefined method `set_preference' for nil:NilClass
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.3/lib/active_support/whiny_nil.rb:48:in `method_missing'
/Library/Ruby/Gems/1.8/gems/spree_core-0.40.0/lib/spree/preference_access.rb:18:in `set'
/Library/Ruby/Gems/1.8/gems/spree_core-0.40.0/lib/spree/preference_access.rb:17:in `each'
/Library/Ruby/Gems/1.8/gems/spree_core-0.40.0/lib/spree/preference_access.rb:17:in `set'
/Library/Ruby/Gems/1.8/gems/spree_solr_search-0.30.0.beta1/lib/spree_solr_search.rb:11:in `activate'
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `_callback_before_39'
```

full error: http://pastebin.com/MRMXtT7q

Thanks a lot for your help and your spree plugin.

Alex

**Comment by romul** [comment]
Looks like you install extension before bootstraping database.

**Comment by alx** [comment]
Ok, here is the list of commands on a fresh spree install to index products with solr_search:

```
rake db:create
rake db:bootstrap
```

Add "_gem 'spree_solr_search'_" in your _Gemfile_, then:

```
rake solr:reindex BATCH=500
```

On dev machine, jetty-solr is used (to be started before launching _solr:reindex_ task):

```
git clone https://github.com/dcrec1/jetty-solr.git
cd jetty-solr
./start
```

**Comment by romul** [comment]
1) I can't reproduce your error
2) `undefined method 'set_preference' for nil:NilClass` is not related directly to solr_search, this error is about empty database, b/c Spree::Config.instance is nil if this error shown. In new version of solr_search added guard condition for this case.

Normally output of `rake solr:reindex BATCH=500` is

```
Clearing index for Product...
Rebuilding index for Product...
Optimizing...
```

I don't know why your Solr installation can't handle Optimizing step, maybe it's misconfigured. In any case this rake task is a part of https://github.com/dcrec1/acts_as_solr_reloaded
