### ISSUE TITLE
Pagination Issue

### ISSUE THREAD

**Issue by nwwatson** [romul/spree-solr-search#6]
Using spree-solr-search 1.4.0 with Spree 0.11.0, apache2, passenger, Ubuntu 10.04, Ruby 1.8.7. Also tested an verified on Mac OSX w/non-Apple Ruby 1.8.7 on RVM.

When searching for products, pagination works as expected, however when browsing taxons, pagination does not work. Upon further inspection, I put logging in right before and after the following line in /lib/spree/search.rb

curr_page = Spree::Config.searcher.manage_pagination ? 1 : params[:page]

Spree::Config.searcher.manage_pagination returns TRUE as e defined in solr_search/lib/spree/solr.rb prepare method as expected. The base search implementation does not implement the method, therefore searcher returns nil causing the params[:page] value to be used for pagination.

Browsing taxonomy tags appears to need the value to be nil, to properly do paging, while the search message requires true. If you want to see a live working example, I can send you links to the problem on my site.

**Comment by romul** [comment]
You need update your Spree version to 0.11.2
This issue was fixed long time ago.

**Comment by greengrass** [comment]
I cant update to spree version  0.11.2, I was wondering what code could be replaced in spree 0.11.0 to get this working, thanks.
