### ISSUE TITLE
warning: already initialized constant RAILS_ROOT

### ISSUE THREAD

**Issue by vandrijevik** [romul/spree-solr-search#8]
After adding spree_solr_search to a spree app (spree version "0.50.99"), I get this warning:

```
/ruby/default/gems/gems/spree_solr_search-0.40.0/lib/../app/controllers/spree/base_controller_decorator.rb:3: warning: already initialized constant RAILS_ROOT
```

on every request made when running the app, as well as when running tests.

**Comment by pronix** [comment]
Change it to Rails.root.to_s

**Comment by vandrijevik** [comment]
pronix, I am not sure what you mean by "Change it to Rails.root.to_s".

If you take a look at the offending code (https://github.com/romul/spree-solr-search/blob/master/app/controllers/spree/base_controller_decorator.rb#L3) you'll see that the problem is that spree_solr_search redefines RAILS_ROOT.

I don't know why the gem does this, so instead of just a Pull Request which eliminates that line, I filed an issue to get more info.

**Comment by pronix** [comment]
You are right.
realy bug.

**Comment by romul** [comment]
This is not a bug, this is just a warning. That's needed, b/c acts_as_solr_reloaded uses RAILS_ROOT. Although it's defined also in https://github.com/romul/spree-solr-search/blob/master/lib/tasks/acts_as_solr.rake#L5, and it is needed in both places. 
In both places can be added `unless defined?(RAILS_ROOT)`,  although there is no practical benefit from this.

**Comment by romul** [comment]
fixed
