### ISSUE TITLE
spree_solr_search breaks RSpec 2.5 specs on Rails 3

### ISSUE THREAD

**Issue by vandrijevik** [romul/spree-solr-search#9]
By overriding ENV['RAILS_ENV'], https://github.com/romul/spree-solr-search/blob/master/lib/spree_solr_search.rb#L8 breaks running tests with RSpec 2.5. In particular, the `spec/spec_helper.rb` generated by RSpec contains the line:

```
ENV["RAILS_ENV"] ||= 'test'
```

Because of the conditional assignment, when spree_solr_search is added to a project, RAILS_ENV is always "development" when running tests, as engines are activated before spec/spec_helper.rb is loaded.

Among other things, this breaks loading of test-only gems with Bundler, so things like factory_girl, shoulda, and other gems which usually go in the test group do not get loaded.

**Comment by romul** [comment]
This line needed for correct work of acts_as_solr_reloaded.
1) Why Rails.env == 'development' when you run tests?
2) Have you any suggestions?

**Comment by vandrijevik** [comment]
Rails.env == "development" when I run tests, because in my environment RAILS_ENV is not set, and when I run "rake" Rails defaults it to "development".

The code that sets it (correctly) to "test" is pre-empted by spree_solr_search's code which unconditionally assigns to ENV["RAILS_ENV"]

**Comment by romul** [comment]
Try to run
    rake spec RAILS_ENV=test
